### ISSUE TITLE
Git example not working; clone not working

### ISSUE THREAD

**Issue by aramaki75** [Icinga/icingaweb2-module-incubator#1]
Hello,

following the example for git is currently not working. When I follow the instruction. Icinga shows that not the version 0.5.0 is installed, but dev-master instead. Which results in a dependency problem. 

Only solution that works was the the download of the ZIP file and extricating it in the module directory.

**Comment by buggsdummy** [comment]
Please install a Release version of the IPL module, not the GIT master  <<< yes this is happening to me too

**Comment by buggsdummy** [comment]
Don't clone, just download the zip of the version you're looking for, that works...

**Comment by Thomas-Gelf** [comment]
Should now be fixed
