### ISSUE TITLE
No Debian package for v0.20.0

### ISSUE THREAD

**Issue by jensrudolf** [Icinga/icingaweb2-module-incubator#10]
Latest version on packages.icinga.com is v0.19.0 pulled in from Icinga Director deb package. However, vSphereDB v1.6.0 requires incubator >= v0.20.0. Make it hard to impossible to install vSphereDB 1.6.0 alongside Icinga Director from Debian package repository.

Is there any plan to create a deb package for v0.20.0?

**Comment by lippserd** [comment]
Sorry for the delay. Packages have been uploaded.
