### ISSUE TITLE
Required Version 0.5.999

### ISSUE THREAD

**Issue by famfop** [Icinga/icingaweb2-module-incubator#5]
I am currently installing icinga2 with Puppet. After installation I found out that the icingaweb2-package does not install the modules it depends on by default but using [this issue](https://github.com/Icinga/puppet-icingaweb2/issues/247) I was able to install them. Actually, I do not really understand why this is not directly written into the module but that is not the point here.

After installation I still see an error in my icingaweb2-UI stating that the required minimum version of the incubator module has to be 0.5.999. I used the 'v0.5.0' tag. So my question is: Which branch or tag should I use in order for the deps. to be fulfilled?

**Comment by Thomas-Gelf** [comment]
You probably installed a recent master of either vSphereDB or Director. We're currently preparing new releases for both of then, and the `incubator` module is still getting quite some related updates. Please use the latest v0.6.0-beta* release, that will satisfy the required dependency. The most recent one is [v0.6.0-beta3](https://github.com/Icinga/icingaweb2-module-incubator/releases/tag/v0.6.0-beta3)

**Comment by famfop** [comment]
Thank you, this solved the issue.
